version: "3.8"
services:
  # rabbitmq:
  #   image: rabbitmq:3.12.14-management
  #   restart: unless-stopped
  #   volumes:
  #     - rabbit_data:/var/lib/rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  postgres:
      restart: always
      image: docker.io/bitnami/postgresql:14
      container_name: bettermode-postgres
      volumes:
        - "postgres_data:/bitnami/postgresql"
      ports:
        - 5432:5432
      environment:
        POSTGRESQL_USERNAME: postgres
        POSTGRESQL_PASSWORD: postgres
        POSTGRESQL_DATABASE: bettermode_task 

  redis:
    restart: always
    container_name: bettermode-redis
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
    command: redis-server --requirepass mypassword

volumes:
  redis_data:
  rabbit_data:
  postgres_data:
    driver: local